import {
  FaQuestion,
  FaGoogle,
  FaHouse,
  FaUser,
  FaUsers,
  FaLock,
  FaUnlock,
  FaWrench,
  FaTrash,
  FaUpload,
  FaDownload,
  FaShare,
  FaCopy,
  FaPaste,
  FaCheck,
  FaPlus,
  FaMinus,
  FaArrowUp,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaSpinner,
  FaBell,
  FaEnvelope,
  FaEnvelopeOpen,
  FaCalendar,
  FaClipboard,
  FaComments,
  FaPaperPlane,
  FaCreditCard,
  FaMoneyCheck,
  FaChartPie,
  FaChartLine,
  FaChartArea,
  FaDatabase,
  FaServer,
  FaFolder,
  FaFile,
  FaGlobe,
  FaMap,
  FaLocationArrow,
  FaPhone,
  FaGraduationCap,
  FaBook,
  FaCar,
  FaBuilding,
  FaMoneyBillWave,
  FaChartBar,
  FaCamera,
  FaFileImage,
  FaGear,
  FaPencil,
  FaUserGraduate,
  FaFlag,
  FaInfo,
  FaDisplay,
  FaTags,
  FaTable,
  FaTableList
} from "react-icons/fa6";
import { IconType } from "react-icons/lib";

const Icons: { [key: string]: IconType} = {
  FaQuestion: FaQuestion,
  FaGoogle: FaGoogle,
  FaHouse: FaHouse,
  FaUser: FaUser,
  FaUsers: FaUsers,
  FaLock: FaLock,
  FaUnlock: FaUnlock,
  FaWrench: FaWrench,
  FaTrash: FaTrash,
  FaUpload: FaUpload,
  FaDownload: FaDownload,
  FaShare: FaShare,
  FaCopy: FaCopy,
  FaPaste: FaPaste,
  FaCheck: FaCheck,
  FaPlus: FaPlus,
  FaMinus: FaMinus,
  FaArrowUp: FaArrowUp,
  FaArrowDown: FaArrowDown,
  FaArrowLeft: FaArrowLeft,
  FaArrowRight: FaArrowRight,
  FaSpinner: FaSpinner,
  FaBell: FaBell,
  FaEnvelope: FaEnvelope,
  FaEnvelopeOpen: FaEnvelopeOpen,
  FaCalendar: FaCalendar,
  FaClipboard: FaClipboard,
  FaComments: FaComments,
  FaPaperPlane: FaPaperPlane,
  FaCreditCard: FaCreditCard,
  FaMoneyCheck: FaMoneyCheck,
  FaChartPie: FaChartPie,
  FaChartLine: FaChartLine,
  FaChartArea: FaChartArea,
  FaDatabase: FaDatabase,
  FaServer: FaServer,
  FaFolder: FaFolder,
  FaFile: FaFile,
  FaGlobe: FaGlobe,
  FaMap: FaMap,
  FaLocationArrow: FaLocationArrow,
  FaPhone: FaPhone,
  FaGraduationCap: FaGraduationCap,
  FaBook: FaBook,
  FaCar: FaCar,
  FaBuilding: FaBuilding,
  FaMoneyBillWave: FaMoneyBillWave,
  FaChartBar: FaChartBar,
  FaCamera: FaCamera,
  FaFileImage: FaFileImage,
  FaGear: FaGear,
  FaPencil: FaPencil,
  FaUserGraduate: FaUserGraduate,
  FaFlag: FaFlag,
  FaInfo: FaInfo,
  FaDisplay: FaDisplay,
  FaTags: FaTags,
  FaTable: FaTable,
  FaTableList: FaTableList,
};


export default Icons